### ISSUE TITLE
Running error

### ISSUE THREAD

**Issue by gabrielspadon** [chanhanyi0923/KDEEB#1]
Hi!

I'm trying to use your code, but when using `./bin/main` I'm getting:

> Detected 0 devices
> eglCreateContext failed

Do you have any idea why?

**Comment by hanych923** [comment]
Maybe it is a driver issue?
I didn't have experience about this error. I only tested my program on Nvidia GTX 1080 Ti on Ubuntu 16.04 with nvidia-396 driver.

**Comment by gabrielspadon** [comment]
I installed the same OS as you and the same driver too (on a Nvidia GTX 1060).
Now I'm getting this message:

> Detected 1 devices
> Configuration not found

Any idea?

**Comment by hanych923** [comment]
Oh sorry I didn't upload configuration file and test input data.

About configuration:
you need to modify '/home/hanyi/KDEEB/others/test7/iteration.conf' to your path at Application.cpp:184
and the format of iteration.conf:
```
count(int) textureWidth(int) kernelSize(float) attractionFactor(double) smoothingFactor(double) doResamplingString(true or false)
```

This is the parameter I use:
```
20 200 20 0.01 0.1 true
```

Application.cpp:541
Application_Input.cpp:14
Application_Input.cpp:34
Application_Input.cpp:64
may also need to be changed, really sorry about this. 😥

**Comment by gabrielspadon** [comment]
There is no problem at all!
Still, I think we might have some other problems.
I noticed that there are more 3 files with full (not relative) paths.
These paths are pointing to files and folders there are not within the repository.
Do you mind checking it or sending me a zip of your full repository?
This is my e-mail if will want to talk to me directly gabriel@spadon.com.br
